export const skills = [
  'Networking',
  'Windows Repair',
  'Mac Repair',
  'iOS Support',
  'Android Support',
  'Server Setup',
  'Cloud Migration',
  'Active Directory',
  'CCTV Installation',
  'Smart Home',
  'Data Recovery',
  'Virus Removal',
  'Hardware Repair',
  'Laptop Screen Replacement',
  'Printer Setup',
  'WiFi Setup',
  'Office 365',
  'VMware',
  'Email Configuration',
  'Cable Management',
  'Software Installation',
  'Security Systems',
]

export const nswSuburbs = [
  'Alexandria', 'Artarmon', 'Ashfield', 'Balmain', 'Bondi', 'Bondi Junction',
  'Brookvale', 'Chatswood', 'Chippendale', 'Coogee', 'Crows Nest', 'Darlinghurst',
  'Dee Why', 'Double Bay', 'Drummoyne', 'Erskineville', 'Fairfield', 'Freshwater',
  'Glebe', 'Gordon', 'Granville', 'Harris Park', 'Haymarket', 'Hornsby',
  'Hurstville', 'Kingsford', 'Kogarah', 'Lane Cove', 'Leichhardt', 'Liverpool',
  'Manly', 'Marrickville', 'Merrylands', 'Mosman', 'Neutral Bay', 'Newtown',
  'North Sydney', 'Parramatta', 'Penrith', 'Pyrmont', 'Randwick', 'Redfern',
  'Ryde', 'St Leonards', 'St Peters', 'Strathfield', 'Surry Hills', 'Sydney CBD',
  'Ultimo', 'Westmead', 'Willoughby',
]

export const serviceTypes = [
  'Computer Repair',
  'Laptop Repair',
  'Screen Replacement',
  'Virus/Malware Removal',
  'Data Recovery',
  'Network Setup',
  'WiFi Installation',
  'Server Setup',
  'Cloud Migration',
  'CCTV Installation',
  'Smart Home Setup',
  'Printer Setup',
  'Software Installation',
  'Office 365 Setup',
  'Email Configuration',
  'Hardware Upgrade',
  'System Tune-up',
  'Emergency Call-out',
]
